#!/bin/bash

options=(
	style=round
	width=3.0
  blur_radius=12.0
	hidpi=on
  ax_focus=on
  order=above
	"active_color=gradient(top_left=0xff00cccc,bottom_right=0xffba3aa5)" 
	"inactive_color=gradient(top_left=0xaa45c4c0,bottom_right=0xaaba3aa5)" \
)

borders "${options[@]}"
