# Terminal
  matches:

  - trigger: "sshpi"
    replace: "ssh tb@192.168.10.169"

  - trigger: "cdesp"
    replace: "cd /Users/tb/Library/'Application Support'/espanso/match/"

  - trigger: ":tmnew"
    replace: "tmux new -s "
  
  - trigger: ":gr"
    replace: "| grep '$|$' "
    word: true

  - trigger: ":le"
    replace: "| less "
    word: true

  - trigger: "icat"
    replace: "kitty +kitten icat "

  - trigger: "estop"
    replace: "espanso stop"

# ____________________
# Ghostty related
  - trigger: "gh-theme"
    replace: "ghostty +list-themes"

  - trigger: "gh-keys"
    replace: "ghostty +list-keybinds | less"

  - trigger: "gh-fonts"
    replace: "ghostty +list-fonts | less"

  - trigger: "gh-actions"
    replace: "ghostty +list-actions | less"

# ____________________
# 
  - trigger: ":mkdir"
    replace: "mkdir -p {{newfolder.folder}} && cd {{newfolder.folder}}"
    vars:
      - name: newfolder
        type: form
        params:
          layout: "Folder name: [[folder]]"
