#!/bin/bash

  source "$CONFIG_DIR/init.lua"
  source "$CONFIG_DIR/colors.sh"
  PLUGIN_DIR="$CONFIG_DIR/plugins"
  ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
  sketchybar --bar position=bottom height=50 color=$TRANSPARENT_COLOR
  sketchybar --animate sin 30 --bar y_offset=10 y_offset=0
##### Changing Defaults #####
# https://felixkratz.github.io/SketchyBar/config/items
  default=(                                             \
      icon.font="Symbols Nerd Font Mono:Regular:15.0"   \
      label.font="OperatorMono Nerd Font:MediumItalic:15.0"     \
      icon.color=$PURPLE_60                             \
      label.color=$PURPLE_80                             \
      icon.padding_left=2                               \
      icon.padding_right=2                              \
      label.padding_left=2                              \
      label.padding_right=2                           
    )

  sketchybar --default "${default[@]}"

# -- Left Side Items --
  source $ITEM_DIR/spaces.sh
  source $ITEM_DIR/front_app.sh

# -- Center items --
  source $ITEM_DIR/spotify.sh

# --- Right Side Items ---
#  #source $ITEM_DIR/weekday.sh
#  source $ITEM_DIR/clock.sh
#  source $ITEM_DIR/calendar.sh
#  source $ITEM_DIR/volume.sh
#  source $ITEM_DIR/battery.sh
#  source $ITEM_DIR/cpu.sh

#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update
