#!/bin/bash

  source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors


  source "$CONFIG_DIR/colors.sh"
  source "$CONFIG_DIR/icons.sh" 
  
  ITEM_DIR="$CONFIG_DIR/items" 
  PLUGIN_DIR="$CONFIG_DIR/plugins"
  
  FONT_ICON="SF Pro"
  FONT_TEXT="OperatorMono Nerd Font"
 
#_________________________________________________\
  sketchybar --bar height=30 \
  	color="$BAR_COLOR" \
  	shadow="$SHADOW" \
  	position=top \
  	sticky=on \
  	padding_right=0 \
  	padding_left=3 \
  	corner_radius="$CORNER_RADIUS" \
  	y_offset=5 \
  	margin=5 \
  	blur_radius=20 \
  	notch_width=200 \
  	--default updates=when_shown \
  	icon.font="$FONT:Bold:13" \
  	icon.color="$ICON_COLOR" \
  	icon.padding_left="$PADDINGS" \
  	icon.padding_right="$PADDINGS" \
  	label.font="$FONT:BookItalic:15.0" \
  	label.color="$LABEL_COLOR" \
  	label.padding_left="$PADDINGS" \
  	label.padding_right="$PADDINGS" \
  	background.padding_right="$PADDINGS" \
  	background.padding_left="$PADDINGS" \
  	popup.background.border_width=1 \
  	popup.background.corner_radius=11 \
  	popup.background.border_color="$POPUP_BORDER_COLOR" \
  	popup.background.color="$POPUP_BACKGROUND_COLOR" \
  	popup.background.shadow.drawing="$SHADOW" 
#_________________________________________________\
# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center (of notch)
source "$ITEM_DIR/spotify.sh"

# Right tony.b@tutamail.com
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh" 
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

  #defaults=(                                      \
  #  background.height=26                          \
  #  background.corner_radius=8                    \
  #  background.border_width=2                     \
#_#________________________________________________\
  #  icon.font="$FONT_ICON:Bold:14.0"              \
  #  icon.color=$mint_60                           \
  #  icon.padding_right=5                          \
#_#________________________________________________\
  #  label.font="$FONT_TEXT:Medium:16.0"     \
  #  label.color=$purple_80                        \
  #  label.padding_right=$PADDINGS                 \
  #  label.y_offset=1                              \
#_#________________________________________________\
  #  popup.background.border_width=2               \
  #  popup.background.corner_radius=8              \
  #  popup.background.border_color=$mint_80        \
  #  popup.background.color=$dark_color            \
  #  popup.blur_radius=12                          \
  #  popup.background.shadow.drawing=on            \
  #  updates=when_shown                            \
  #  scroll_texts=on
  #)
  
#  sketchybar --bar "${bar[@]}"
#  sketchybar --default "${defaults[@]}"
#  sketchybar --animate sin 30 --bar y_offset=10 y_offset=0
#
#  # Left
#  source "$ITEM_DIR/apple.sh"
#  source "$ITEM_DIR/yabai.sh"
#  source "$ITEM_DIR/spaces.sh"
#  source "$ITEM_DIR/front_app.sh"
#  
#  # Center
#  source "$ITEM_DIR/spotify.sh"
#  
#  # Right
#  source "$ITEM_DIR/calendar.sh"
#  source "$ITEM_DIR/wifi.sh"
#  source "$ITEM_DIR/battery.sh"
#  source "$ITEM_DIR/volume.sh"
#  source "$ITEM_DIR/cpu.sh"
  
  # Forcing all item scripts to run (never do this outside of sketchybarrc)
  sketchybar --update
  sketchybar --hotload on
  
  echo "sketchybar configuation loaded.."
  #
