#!/bin/bash
# #D56D9F, ##7F9BB1
#
  options=(
  	style=round
  	width=5.0
    blur_radius=12
  	hidpi=on
    ax_focus=on
    order=above
    active_color="gradient(top_left=0xffCA6478,bottom_right=0xff7F9BB1),glow=(0xffA98252)" 
    inactive_color="gradient(top_right=0xff222222,bottom_left=0xff222222"
  )
  borders "${options[@]}"
