# git commands

matches:
  - trigger: "gits"
    replace: "git status"

  - trigger: "git."
    replace: "git add $|$ "

  - trigger: "gitp"
    replace: "git push"

  - trigger: "gitm"
    replace: "git commit -m '$|$'"

  - trigger: "gitcm"
    replace: "git -C /Users/tb/dotfiles_mac add . && git -C /Users/tb/dotfiles_mac commit -m '$|$' "

  - trigger: "gitmain"
    replace: "git checkout main"
    word: true

  - trigger: "gittest"
    replace: "git checkout test"
    word: true
