# git commands

  matches:

  - trigger: "gits"
    replace: "git status"

  - trigger: "git."
    replace: "git add ."

  - trigger: "gitm"
    replace: "git commit -m '$|$' "

  - trigger: "gitp"
    replace: "git push"
  
  - trigger: "gitmain"
    replace: "git checkout main"
    word: true

  - trigger: "gittest"
    replace: "git checkout test"
    word: true

