# git commands

  matches:

  - trigger: "gits"
    replace: "git status"

  - trigger: "gadd"
    replace: "git add ."

  - trigger: "gcm"
    replace: "git commit -m '$|$' "

  - trigger: "gcup"
    replace: "git commit -m 'update' "

  - trigger: "gcfix"
    replace: "git commit -m 'fix' "

  - trigger: "gpush"
    replace: "git push"
  
  - trigger: "gitmain"
    replace: "git checkout main"
    word: true

  - trigger: "gittest"
    replace: "git checkout test"
    word: true

