# espanso match file 

  matches:

# ____________________________________________
# scrcpy open external display + best keyboard/mouse options
  - trigger: ":scrcpy-sdk"
    replace: "scrcpy --disable-screensaver --keyboard sdk --mouse sdk --new-display"

  - trigger: ":bt"
    replace: "bzmenu -l walker"

  - trigger: ":shizuku-start"
    replace: "adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh"

  - trigger: ":uber"
    replace: "cd /Users/tb/Library/'Application Support'/Übersicht"

  - trigger: ":bar"
    replace: "cd /Users/tb/Library/'Application Support'/Übersicht/widgets/simple-bar"
# ____________________________________________
# Terminal 
  - trigger: "icat"
    replace: "kitty +kitten icat $|$"
    word: true

  - trigger: ":mkdir"
    replace: "mkdir -p {{form1.folder}} && cd {{form1.folder}}"
    vars:
      - name: form1
        type: form
        params:
          layout: "Folder name: [[folder]]"

  - trigger: ":div"
    replace: "<div>$|$</div> "

  - trigger: ":grep"
    replace: "| grep '$|$' "

  - trigger: ":less"
    replace: "| less "

  - trigger: 'btctl'
    replace: 'bluetoothctl'
