# espanso match file 

  matches:

# ____________________
# Android related
  - trigger: ":scrcpy-sdk"
    replace: "scrcpy --disable-screensaver --keyboard sdk --mouse sdk --new-display"

  - trigger: ":bt"
    replace: "bzmenu -l walker"

  - trigger: "ubersicht"
    replace: "Übersicht"
  
  - trigger: ":uber"
    replace: "Übersicht"
  
    # ____________________________________________
  # Terminal
  - trigger: ":logout"
    replace: "loginctl kill-user tb"

  - trigger: ":bt"
    replace: "bzmenu -l walker"

  - trigger: ":mkdir"
    replace: "mkdir -p {{form1.folder}} && cd {{form1.folder}}"
    vars:
      - name: form1
        type: form
        params:
          layout: "Folder name: [[folder]]"

  - trigger: ":div"
    replace: "<div>$|$</div> "

  - trigger: ":grep"
    replace: "| grep '$|$' "

  - trigger: ":less"
    replace: "| less "

  - trigger: ":btctl"
    replace: "bluetoothctl"

  - trigger: ":cht"
    replace: "curl cheat.sh/"
