# espanso match file 

  matches:

# ____________________________________________
# Android related
  - trigger: ":scrcpy-sdk"
    replace: "scrcpy --disable-screensaver --keyboard sdk --mouse sdk --new-display"

  - trigger: ":bt"
    replace: "bzmenu -l walker"

  - trigger: ":shizuku-start"
    replace: "adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh"

# ____________________________________________
# Shortcuts (basically Aliases, but I prefer these)
  - trigger: ":uber"
    replace: "cd /Users/tb/Library/'Application Support'/Übersicht"

  - trigger: ":bar"
    replace: "cd /Users/tb/Library/'Application Support'/Übersicht/widgets/simple-bar"
# ____________________________________________
# Terminal 
  - trigger: "icat"
    replace: "kitty +kitten icat $|$"
    word: true

  - trigger: ":mkdir"
    replace: "mkdir -p {{newfolder.folder}} && cd {{newfolder.folder}}"
    vars:
      - name: newfolder
        type: form
        params:
          layout: "Folder name: [[folder]]"

  - trigger: ":grep"
    replace: "| grep '$|$' "

  - trigger: ":less"
    replace: "| less "

# ____________________________________________
# html (wip)
  - trigger: ":html5"
    replace: |
      <!DOCTYPE html>
      <html lang='en'>
        <head>
          <meta charset="UTF-8">
          <meta name='viewport' content='width=device-width, initial-scale=1'>
          <title>Title</title>
          <link href='css/style.css' rel='stylesheet'>
        </head>
        <body>
          $|$
        </body>
      </html>

  - trigger: ":h1"
    replace: <h1>$|$</h1>
  
  - trigger: ":h2"
    replace: <h2>$|$</h2>
  
  - trigger: ":h3"
    replace: <h3>$|$</h3>
  
  - trigger: ":p"
    replace: <p>$|$</p>

  - trigger: ":div"
    replace: |
      <div>
      $|$
      </div>

# ____________________________________________
# CSS (wip)
  - trigger: ":cssclass"
    replace: |
      .

  - trigger: ":class"
    replace: ".{{cssclass.cssclass}} {$|$} "
    vars:
      - name: cssclass
        type: form
        params:
          layout: "Class name: [[cssclass]]"
