# _______________________
# Borders
  set -g pane-border-style 'fg=#3D3D5C' # Inactive panes
  set -g pane-active-border-style 'fg=#BB9AF7' # Active window/pane
  set -g pane-border-indicators colour
  set -g pane-border-status bottom
  set -g pane-border-lines single
  set -g pane-border-format ""
  set -g status-position bottom
 
# _______________________
# statusbar left
  set -g status-justify left
  set -g status-left ''
  set -g status-left-length 15

# _______________________
# General style
  set -gw window-style 'fg=default bg=default' # Colours for inactive panes
  set -gw status-style 'fg=default bg=default' 
# unfocused windows
  set -gw window-status-style 'fg=#6E6A8A bg=default'
  set -gw window-status-format ' #I.#W '
# Active windows
  set -gw window-status-current-style 'fg=#BB9AF7 bg=default bold'
  set -gw window-status-current-format '#I.#[fg=#02AF87]#W '

# _______________________
# Notification alerts
  set -g message-style 'fg=#BB9AF7 bg=default'  # The Notification
  set -g window-status-activity-style 'fg=#F4A7B9 bg=default bold'
  set -g monitor-activity on

# _______________________
# Alerts - general settings
  set -g visual-activity off
  set -g visual-bell off
  set -g visual-silence off
  set -g bell-action none
  #set -g window-status-bell-style 'fg=# bg=default bold'

# _______________________
# statusbar right
  set -g status-right-style 'fg=#BB9AF7 bg=default bold'
  set -g status-right-length 15
  set -g status-right '#{session_name} | %H:%M'
 
# _______________________
# clock mode - keeping that purple
  set -gw clock-mode-colour '#02AF87'
